version: '3.8'

services:
  # 1. Base de Datos Oracle (La necesitamos para guardar los mensajes)
  oracle-db:
    image: gvenzl/oracle-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: admin
    networks:
      - transport-net

  # 2. RabbitMQ (LO NUEVO - Requisito de la rúbrica)
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Puerto interno para que Java se conecte
      - "15672:15672" # Puerto visual para que tú entres desde el navegador
    networks:
      - transport-net

  # 3. Tu Microservicio (Aquí programaremos el consumidor)
  transport-service:
    build: ./transport-service
    ports:
      - "8081:8081"
    environment:
      # Configuración de Oracle
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/xepdb1
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: admin
      # Configuración de RabbitMQ (Para que sepa dónde conectarse)
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - oracle-db
      - rabbitmq
    networks:
      - transport-net

networks:
  transport-net:
    driver: bridge