version: '3.8'

services:
  # 1. Base de Datos Oracle
  oracle-db:
    image: gvenzl/oracle-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: admin
    networks:
      - transport-net

  # 2. RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Puerto interno
      - "15672:15672" # Puerto panel web
    networks:
      - transport-net

  # 3. Tu Consumidor (transport-service)
  transport-service:
    build: ./transport-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/xepdb1
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - oracle-db
      - rabbitmq
    networks:
      - transport-net

  # 4. Tu Nuevo Productor (BFF) - Â¡ESTO FALTABA!
  transport-bff:
    build: ./transport-bff
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    depends_on:
      - rabbitmq
    networks:
      - transport-net

networks:
  transport-net:
    driver: bridge